SELECT COUNT(*) 
FROM SACH_BANSAO
WHERE Mãsách = (SELECT Mãsách FROM SACH WHERE Tênsách = 'The Lost Tribe')
  AND Mãnhánh = (SELECT Mãnhanh FROM NHANH_THUVIEN WHERE Tênnhánh = 'Shapstown');

SELECT NHANH_THUVIEN.Tênnhánh, COUNT(*)
FROM SACH_BANSAO
JOIN NHANH_THUVIEN ON SACH_BANSAO.Mãnhánh = NHANH_THUVIEN.Mãnhanh
WHERE Mãsách = (SELECT Mãsách FROM SACH WHERE Tênsách = 'The Lost Tribe')
GROUP BY NHANH_THUVIEN.Tênnhánh;

SELECT NGUOIMUON.Tên
FROM NGUOIMUON
LEFT JOIN SACH_MUON ON NGUOIMUON.Sốthẻ = SACH_MUON.Sốthẻ
WHERE SACH_MUON.Sốthẻ IS NULL;

SELECT SACH.Tênsách, NGUOIMUON.Tên, NGUOIMUON.Địachỉ
FROM SACH_MUON
JOIN SACH ON SACH_MUON.Mãsách = SACH.Mãsách
JOIN NGUOIMUON ON SACH_MUON.Sốthẻ = NGUOIMUON.Sốthẻ
WHERE SACH_MUON.Mãnhánh = (SELECT Mãnhanh FROM NHANH_THUVIEN WHERE Tênnhánh = 'Shapstown')
  AND SACH_MUON.Ngàytrả = CURDATE();

SELECT NHANH_THUVIEN.Tênnhánh, COUNT(SACH_MUON.Mãsách) AS "Tổng số sách được mượn"
FROM NHANH_THUVIEN
LEFT JOIN SACH_MUON ON NHANH_THUVIEN.Mãnhanh = SACH_MUON.Mãnhánh
GROUP BY NHANH_THUVIEN.Tênnhánh;

SELECT NGUOIMUON.Tên, NGUOIMUON.Địachỉ, COUNT(SACH_MUON.Mãsách) AS "Số sách mượn"
FROM NGUOIMUON
JOIN SACH_MUON ON NGUOIMUON.Sốthẻ = SACH_MUON.Sốthẻ
GROUP BY NGUOIMUON.Tên, NGUOIMUON.Địachỉ
HAVING COUNT(SACH_MUON.Mãsách) > 5;

